spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        generate_statistics: 'false'
        format_sql: 'true'
    database: postgresql
    hibernate:
      ddl-auto: update
    show-sql: 'true'
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  jackson:
    deserialization:
      unwrap-root-value: 'false'
    serialization:
      FAIL_ON_SELF_REFERENCES: 'false'
      FAIL_ON_EMPTY_BEANS: 'false'
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  session:
    store-type: jdbc
    jdbc:
      initialize-schema: always
    timeout:
      seconds: '600'
  datasource:
    password: postgres
    username: postgres
    url: jdbc:postgresql://java_db:5432/postgres
    hikari:
      auto-commit: false
  sql:
    init:
      encoding: UTF-8
jwt:
  secret: javainuse
server:
  port: '8080'